name: wakeup_proof
description: Sveglia anti-snooze con challenge verificati on-device e abbonamenti.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # Storage & DB
  sqflite: ^2.3.0
  sqlcipher_flutter_libs: ^0.6.1
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  # Sensors & device
  sensors_plus: ^5.0.2
  connectivity_plus: ^6.0.3
  bluetooth_low_energy: ^0.5.0 # valuta alternativa se necessario
  # QR / Camera
  mobile_scanner: ^3.5.7
  camera: ^0.10.5+9
  # NFC (scegline uno in base al device)
  nfc_manager: ^3.3.0
  # ML / ONNX
  onnxruntime_flutter: ^1.16.3
  # Firebase (Auth/Firestore/Functions - opzionali in MVP offline)
  firebase_core: ^3.4.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.4.4
  cloud_functions: ^5.1.3
  # In-app purchase (se preferisci store-native invece di Stripe web)
  in_app_purchase: ^3.1.13
  # State management (scegli secondo gusto)
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
