name: wakeup-proof
services:
- name: web
  source_dir: /
  github:
    repo: username/wakeup-proof
    branch: main
  run_command: echo "Static site - no run command needed"
  environment_slug: static
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  static_sites:
  - name: wakeup-proof
    source_dir: /
    github:
      repo: username/wakeup-proof
      branch: main
    routes:
    - path: /